### ISSUE TITLE
eulfedora not compatible with requests 2.11.0

### ISSUE THREAD

**Issue by cormier** [emory-libraries/eulfedora#25]
Since version 2.11.0 requests expects header attributes to be of type str or bytes:
https://github.com/kennethreitz/requests/blob/fb014560611f6ebb97e7deb03ad8336c3c8f2db1/requests/utils.py#L754

eulfedora specify the verify attribute as a bool:
https://github.com/emory-libraries/eulfedora/blob/master/eulfedora/api.py#L91

This causes requests to raise InvalidHeader exceptions when eulfedora uses it.

**Comment by rlskoeser** [comment]
@cormier thanks for reporting.  I just discovered this issue via the travis-ci build as I was working on the utf-8 issue raised in #22, and I already have a fix for it on that feature branch.  Hopefully I'll be able to get that branch merged in and get a hotfix out soonish, just hoping to get someone else to verify the utf-8 fixes first.

**Comment by cormier** [comment]
Thanks for the quick reply! In that case I will not submit a fix and continue using requests 2.10.0 in the meantime.

**Comment by rlskoeser** [comment]
Fixed in eulfedora 1.7.2
