### ISSUE TITLE
add_relationship() does not recognize object PIDs when provided as unicode strings

### ISSUE THREAD

**Issue by ghukill** [emory-libraries/eulfedora#9]
Perhaps this is not a bug, and just how unicode and string objects are treated differently with Eulfedora, but it has caused us various bouts of confusion when creating relationships with `add_relationship`, and thought it might be worth mentioning.

When using `add_relationship()`, if you provide unicode objects instead of plain strings, they are not added as `rdf:resource` to the triple, but instead, as string literals.  

For example, `object_handle.add_relationship(u'fedora-rels-ext:hasContentModel',u'info:fedora:CM:Collection')` 

would create the RELS-EXT triple, `<hasContentModel xmlns="info:fedora/fedora-system:def/relations-external#">info:fedora/CM:Collection</hasContentModel>`

Where, `object_handle.add_relationship('fedora-rels-ext:hasContentModel','info:fedora:CM:Collection')` 

would create, `<hasContentModel xmlns="info:fedora/fedora-system:def/relations-external#" rdf:resource="info:fedora/CM:Collection"></hasContentModel>`

Now that we know to look out for that, it's relatively easy to manage for, but was not obvious at first.

**Comment by rlskoeser** [comment]
Looks like a bug.  Thanks for pointing it out.

**Comment by rlskoeser** [comment]
@ghukill just committed a fix in develop.  Should go out in the next release.

**Comment by ghukill** [comment]
That's great!  Many thanks.
